### ISSUE TITLE
Payee data source fix/improvements

### ISSUE THREAD

**Issue by hpernu** [martinohansen/ynabber#25]
There has been discussion and various attempts to make modifications to where YNAB payee data actually comes from.
The current implementation uses parts of RemittanceInformationUnstructured i.e. parts of what goes to Memo.

This is an issue for the author of this ticket and also apparently for the user who made [PR #10](https://github.com/martinohansen/ynabber/issues/10) as well.

There are also several branches with suggested solutions. The primary ones being:
- use creditorName/debtorName as payee - never use RemittanceInformationUnstructured
- as above but use the normal behavior as fallback if there is nothing in creditorName or debtorName
- bank id specific coding

The first two were apparently not good for at least the repository owner usage. The coding by bank is likely hard to maintain and would require constant modification if/when new banks are being used.

For me the current solution is memo is nonetheless useless and I have to fix all payees by hand(mostly they are empty).
I am opening this issue so that we could avoid yet another attempt and instead discuss the appropriate solution first with perhaps some insight from other users. 

Backwards compatibility may be an issue but I am not against breaking it on occasion. Even big companies (Microsoft/Apple) do it on occasion and the userbase here is miniscule. Just make this something that works for current users and seems right for the near future without too much maintenance.

**Comment by hpernu** [comment]
My current/new suggestion:
- use environment variable YNAB_PAYEE
- it can have comma separated list of values such as name(=creditorName/debtorName), memo
- the code would use the methods in order they are listed
- the default could be memo,name=old behavior first but if that results in empty string, use creditor/debtor

I am not so sure about the default being the right one. I think it is more common for the creditor/debtor to actually have the payee but there is not enough data to support this. But at least it is backwards compatible mostly. Just using memo would be even more so.

The other thing is the choice of environment variable name and where this change should actually go to. Logically this would be in Nordigen reader part but much of the memo and payee cleaning is now done in ynab writer.

**Comment by martinohansen** [comment]
> My current/new suggestion:
> 
> - use environment variable YNAB_PAYEE
> 
> - it can have comma separated list of values such as name(=creditorName/debtorName), memo
> 
> - the code would use the methods in order they are listed
> 
> - the default could be memo,name=old behavior first but if that results in empty string, use creditor/debtor
> 
> 
> 
> I am not so sure about the default being the right one. I think it is more common for the creditor/debtor to actually have the payee but there is not enough data to support this. But at least it is backwards compatible mostly. Just using memo would be even more so.
> 
> 
> 
> The other thing is the choice of environment variable name and where this change should actually go to. Logically this would be in Nordigen reader part but much of the memo and payee cleaning is now done in ynab writer.
> 
> 

This all sounds good, having it to be a dynamic mapping configured by the users is desirable.

This should go into the Nordigen reader and let's not make any breaking changes at this point in time. 

Thanks for working on this.
