### ISSUE TITLE
Outflow & Inflow mapping swapped

### ISSUE THREAD

**Issue by pfFredd** [martinohansen/ynabber#47]
For bank id SEB_KORT_AB_NO_SKHSFI21 outflow and inflow columns in YNAB are swapped so purchases appear as inflow and refunds/downpayments appear as outflow. 

This is a credit card so the logic is probably reversed from the card issuer compared to a normal account. 

Here are two examples with the response from Nordigen along with the imported transactions in YNAB:

![Greenshot 2023-02-26 17 39 40](https://user-images.githubusercontent.com/2168773/221424119-029d232d-1ba1-47c3-aaaa-809af01d22bf.png)
![Greenshot 2023-02-26 17 40 22](https://user-images.githubusercontent.com/2168773/221424122-00da0275-65b7-41a5-899d-8b7a9cbecd44.png)
![Greenshot 2023-02-26 17 41 14](https://user-images.githubusercontent.com/2168773/221424124-e41f2153-7a3f-4df7-936f-eb6aa561598c.png)

**Comment by martinohansen** [comment]
Is it like that for all accounts or just some? I'm wondering if we need to add a single or a per account toggle to swap in/out flow.

**Comment by pfFredd** [comment]
I have two other bank connections that seem to map correctly. Therefore, it seems to be isolated to this one at least from the connections I tested with.On 26 Feb 2023, at 18:21, Martin Hansen ***@***.***> wrote:﻿
Is it like that for all accounts or just some? I'm wondering if we need to add a single or a per account toggle to swap in/out flow.

**Comment by hpernu** [comment]
> I have two other bank connections that seem to map correctly. Therefore, it seems to be isolated to this one at least from the connections I tested with.

Are the other bank connection to a bank with a different bank id or the same one?
It is important to know whether this is bank or account specific.

**Comment by pfFredd** [comment]
> > I have two other bank connections that seem to map correctly. Therefore, it seems to be isolated to this one at least from the connections I tested with.
> 
> Are the other bank connection to a bank with a different bank id or the same one? It is important to know whether this is bank or account specific.

It seems to be a bank specific the two other connections are with two other banks, and there it works as it should.

**Comment by martinohansen** [comment]
@pfFredd please test with the image from PR #48. I added this config option:

```golang
// SwapFlow changes inflow to outflow and vice versa for any account with a
// IBAN number in the list. This is, for example, relevant for credit card
// accounts.
//
// Example: "DK9520000123456789,NO8330001234567"
SwapFlow []string `envconfig:"YNAB_SWAPFLOW"`
```

**Comment by pfFredd** [comment]
> @pfFredd please test with the image from PR #48. I added this config option:
> 
> ```go
> // SwapFlow changes inflow to outflow and vice versa for any account with a
> // IBAN number in the list. This is, for example, relevant for credit card
> // accounts.
> //
> // Example: "DK9520000123456789,NO8330001234567"
> SwapFlow []string `envconfig:"YNAB_SWAPFLOW"`
> ```

Works as a charm! Thanks :-)
