### ISSUE TITLE
Requisition creation fails to save new requisition for some banks

### ISSUE THREAD

**Issue by hpernu** [martinohansen/ynabber#49]
I am facing this problem with NORWEGIAN_FI_NORWNOK1  - possibly it affects other banks as well.

The requisition creation proceeds normally up to the point when the browser display https://raw.githubusercontent.com/martinohansen/ynabber/main/ok.html . But then the command line client remains stuck forever(or until timeout).

I tried with another bank and that works. Do you have any idea what might be going on?

I already have debugging on but nothing is displayed on console.

**Comment by martinohansen** [comment]
Sounds like it hangs around here: https://github.com/martinohansen/ynabber/blob/b2469641318825421e1a0b4a8ea6a79af7203321/reader/nordigen/auth.go#L99-L107

What happens if you call the API yourself to check what it returns? https://github.com/frieser/nordigen-go-lib/blob/319e8893bdc84370aac944feba00a7003866c504/requisitions.go#L74-L102

**Comment by hpernu** [comment]
Hmm ... apparently this is a problem between Nordigen and Norwegian Bank.
Trying from the Nordigen web interface, which I use to test bank data connections sometimes, I get:
{
    "summary": "Couldn't update account transactions",
    "detail": "Request to Institution returned an error"
}

Details are not very helpful ...

But if it does not work there it will not work with ynabber either.
I am curious though why ynabber does not return an error but is stuck there instead until timeout.

You can disregard this as a real issue unless you here an independent report facing the same problem and we can see it is related to ynabber/related libraries.

**Comment by hpernu** [comment]
Resolution: problem is between Nordigen and the bank in question. Although preferably ynabber should exit with an error in these cases it is nonetheless a different issue.

**Comment by martinohansen** [comment]
Yeah, in Ynabber, we're just waiting for for the requisition to go through indefinitely. That could be improved with some error checks for sure.

**Comment by hpernu** [comment]
I reported this to Nordigen instead and got this response:
I have located the error. It is rather unique, it seems we will require to reach out to the bank to investigate this further. Hopefully a fix will be introduced quickly.

So the original error really is not related to ynabber.

**Comment by martinohansen** [comment]
The world is unique and fallible, so I'm gonna keep this issue open and label it was enhancement and good first issue.

We should handle such error cases better.
