### ISSUE TITLE
Multiplication of transactions with Sparebank 1 Østlandet in v0.7.1

### ISSUE THREAD

**Issue by ingvarso** [martinohansen/ynabber#64]
In latest version v0.7.1 transactions from Sparebank 1 Østlandet are multiplied in ynab. From my first investigations it seems like the ynabber doesn't honor the "InternalTransactionId" environment variable, which is needed for sane behavior with Sparebank 1
```
NORDIGEN_TRANSACTION_ID=InternalTransactionId
```

**Comment by ingvarso** [comment]
Oh... I can see there is a major rewrite of how to configure... Does it mean you need config details for each bank to set it up? I currently have it working with Sparebank 1 Østlandet, Circle K (SEB) and Morrow bank.

**Comment by ingvarso** [comment]
This is my current setup:

### Sparbank 1 Østlandet:
- Need to use InternalTransactionId
```
NORDIGEN_BANKID=SPAREBANK_OSTLANDET_SHEDNO22
NORDIGEN_TRANSACTION_ID=InternalTransactionId
```
### SEB Kort Bank AB (Circle K Mastercard)
- Needs swapflow enabled

```
NORDIGEN_BANKID=SEB_KORT_AB_NO_SKHSFI21
YNAB_SWAPFLOW=***************
```
### Morrow bank
- Works out of the box
```
NORDIGEN_BANKID=MORROW_NDEANOKK
```

**Comment by martinohansen** [comment]
Hi 👋 

I'm sorry for the trouble the duplicate entries caused, I know it can be a hassle to clean up.

I reintroduced the `NORDIGEN_TRANSACTION_ID` config option here: #65 please test and let me know if that works for you. Its also available as a docker image with tag: [pr-65](https://github.com/users/martinohansen/packages/container/ynabber/168145752?tag=pr-65)

The goal is to support every bank with individual mappers but unfortunately, it's not that easy to do. If you can provide me with a full transaction payload from your banks (you can get that with debugging turned on) I can make specific mappers for you that suit your needs. 

Someday we should implement a way for the user to have complete control over the mapping between bank and ynabber.

**Comment by ingvarso** [comment]
Thanks! Tested the pr-65 docker image, and it seems to work without any duplication.

**Comment by al-automasjon** [comment]
For me it seems like they introduced a new field in Sparebanken to proprietaryBankTransactionCode - the internalTransactionId is not different for even the same transaction for example a bill, so it seems like we need to add more properties here
