### ISSUE TITLE
Ynabber no longer honors NORDIGEN_DATAFILE environment variable

### ISSUE THREAD

**Issue by hpernu** [martinohansen/ynabber#69]
This is needed as I otherwise get conflicting file names in data directory.

The specific need here is that I have two user accounts to same bank. They need a different requisition and login credentials.
So naming the file just based on BIC code is not enough.

**Comment by hpernu** [comment]
Apparently it is now on this line:
https://github.com/martinohansen/ynabber/blob/b2d89b434927fe2ea8dda7fed9e3e9462c5f4b2d/reader/nordigen/auth.go#L21

And no possibility to use anything but the bankID. This is not enough for me. A separate user settable extra value would be needed(or complete override as the NORDIGEN_DATAFILE used to be).

I can, of course, create batch. But until it'd be on main, I am forced to use the older version, which does not have new Gocardless URLs. And I am not sure we agree on how this would be best handled. The previous solution obviously was not okay for you.

**Comment by martinohansen** [comment]
> Apparently it is now on this line:
> 
> https://github.com/martinohansen/ynabber/blob/b2d89b434927fe2ea8dda7fed9e3e9462c5f4b2d/reader/nordigen/auth.go#L21
> 
> And no possibility to use anything but the bankID. This is not enough for me. A separate user settable extra value would be needed(or complete override as the NORDIGEN_DATAFILE used to be).
> 
> I can, of course, create a patch. But until it'd be on main, I am forced to use the older version, which does not have new Gocardless URLs. And I am not sure we agree on how this would be best handled. The previous solution obviously was not okay for you.

You should be able to change it with `YNABBER_DATADIR`

```
export YNABBER_DATADIR=/foo
export NORDIGEN_BANKID=bar

# Will place file at 
/foo/bar.json
```

**Comment by hpernu** [comment]
> You should be able to change it with `YNABBER_DATADIR`

Yes, I understand that. However, that affects the directory for all requisition files. I have a lot of them, for different banks. Only in one case, there are two userids to the same bank.

> export NORDIGEN_BANKID=bar

Does this really work? Isn't it also used as the bankID in Nordigen(now GoCardless) connection? So this cannot be set to a custom string but must match the real bank exactly.

**Comment by hpernu** [comment]
> > > You should be able to change it with `YNABBER_DATADIR`
> > Yes, I understand that. However, that affects the directory for all requisition files. I have a lot of them, for different banks. Only in one case, there are two userids to the same bank.
> So you want to have multiple requisitions files in the same directory? Will it break for you if you separate it into multiple directories and if so why?

Yes, I have multiple requisition files in the same directory and this is desirable. As long as there is only a single file per requisition/connection anyway, there is no point of creating directories with only a single file in it.

And yes, my current wrappers do break since they assume this behavior i.e. the possibility to use a single directory for multiple requisition. And apparently also the custom name. Why was that possibility removed? Although, I might be the only one using it.

The current implementation on how I am using this does break and there was a reason I implemented the custom filename in the first place. Or did I implement it? Cannot remember anymore but I think the rationale was covered there.

**Comment by martinohansen** [comment]
> > > > You should be able to change it with `YNABBER_DATADIR`
> > > > Yes, I understand that. However, that affects the directory for all requisition files. I have a lot of them, for different banks. Only in one case, there are two userids to the same bank.
> > > > So you want to have multiple requisitions files in the same directory? Will it break for you if you separate it into multiple directories and if so why?
> 
> Yes, I have multiple requisition files in the same directory and this is desirable. As long as there is only a single file per requisition/connection anyway, there is no point of creating directories with only a single file in it.
> 
> And yes, my current wrappers do break since they assume this behavior i.e. the possibility to use a single directory for multiple requisition. And apparently also the custom name. Why was that possibility removed? Although, I might be the only one using it.
> 
> The current implementation on how I am using this does break and there was a reason I implemented the custom filename in the first place. Or did I implement it? Cannot remember anymore but I think the rationale was covered there.

I see. The logic was removed [here](https://github.com/martinohansen/ynabber/commit/91161a141bed526f7afef3ba58b471976e01f94f), which was a mistake. Can you see if this works for you? https://github.com/martinohansen/ynabber/pull/70
