### ISSUE TITLE
Ynab writer and credit card accounts

### ISSUE THREAD

**Issue by linkmic** [martinohansen/ynabber#71]
Hei Martin,

I was informed about your project today and conducted a quick test with SEB Kort Bank, which powers lots of credit cards, including the SAS Eurobonus card. 

The transactions were successfully parsed and written to YNAB using the default mapper. However, they were written to YNAB as inflows instead of outflows. The transactions are returned as positive values from Nordigen.

<img width="871" alt="image" src="https://github.com/martinohansen/ynabber/assets/465961/0b2a8826-022c-4d1e-a26d-8027df9093eb">

Instead of creating a new mapper for this particular bank or provider, you could consider adding a configuration option to invert the sign (+/-) of the transaction's 'Amount' field whenever you have the inclination in the future, which I assume would rectify the problem.

/mike

**Comment by hpernu** [comment]
Just to chime in: I remembered that there is a config option to do exactly this and indeed there is: [https://github.com/martinohansen/ynabber/blob/7f8c6ddaa361d542e1741c8361f3f3e744db3526/config.go#L120-L124](https://github.com/martinohansen/ynabber/blob/7f8c6ddaa361d542e1741c8361f3f3e744db3526/config.go#L120-L124)

Does it look like it'd do what you need?

**Comment by linkmic** [comment]
It does, can't believe I missed that. Thank you.
