### ISSUE TITLE
Config option to filter out future dates

### ISSUE THREAD

**Issue by martinohansen** [martinohansen/ynabber#73]
### Discussed in https://github.com/martinohansen/ynabber/discussions/72

<div type='discussions-op-text'>

<sup>Originally posted by **hoejmann** April 20, 2024</sup>
Not sure where to post ideas, but here I go :)

Some banks, in this case Nordea DK seems to occasionally have a 'bookingDate' and 'valueDate' set in the future, which returns in an error when sending the request to the YNAB API:

```
"bookingDate": "2024-04-22",
"valueDate": "2024-04-22",
```

```
{"error":{"id":"400","name":"bad_request","detail":"date must not be in the future or over 5 years ago (index: 0), date must not be in the future or over 5 years ago (index: 1)"}}
```
Idea: A new config option to automatically filter out dates in the future</div>

**Comment by martinohansen** [comment]
@hoejmann the issue should be fixed in [v0.7.5](https://github.com/martinohansen/ynabber/releases/tag/v0.7.5)

**Comment by hpernu** [comment]
In case you did not read the source code, future dates are always skipped in the new version.

That is, contrary to issue description there is no such config option. The new versions just skip them altogether. Keep your time correct on the system running ynabber.

**Comment by hoejmann** [comment]
Damn you guys move fast! Sweet, thanks. That sounds even better. Appreciate it :)
